# Generated by Django 4.2.30 on 2026-05-05 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_favouriteproducer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRODUCER', 'Producer'), ('CUSTOMER', 'Customer'), ('COMMUNITY-GROUP-REPRESENTATIVE', 'Community-group-representative')], default='CUSTOMER', max_length=50),
        ),
        migrations.CreateModel(
            name='CommunityGroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, default='', max_length=150)),
                ('organization_type', models.CharField(blank=True, default='', help_text='E.g. Educational facility, charity, etc.', max_length=150)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('postcode', models.CharField(blank=True, default='', help_text='Used for Food Miles calculation', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_group_profiles',
            },
        ),
    ]
