# Generated by Django 4.2.30 on 2026-05-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role_communitygroupprofile'),
        ('users', '0010_producerprofile_stripe_account_id'),
    ]

    operations = [
    ]
