# Generated by Django 4.2.30 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='reserved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
