# Generated by Django 4.2.30 on 2026-05-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_recurringorder_recurringorderitem'),
        ('orders', '0008_alter_customerorder_commission_total_and_more'),
    ]

    operations = [
    ]
