# Generated by Django 4.2.30 on 2026-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20260504_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.CharField(blank=True, help_text='Instructions to be left for producers on delivery orders by community group representatives.', max_length=250, null=True),
        ),
    ]
