# Generated by Django 4.2.30 on 2026-05-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_instructions',
            new_name='delivery_instruction',
        ),
    ]
